### ISSUE TITLE
Stickinesses and rates

### ISSUE THREAD

**Issue by yamaguchiyuto** [ntamas/blockmodel#2]
I have some questions.
1. Do stickinesses and rates in the output correspond to theta and omega in the original paper of degree-corrected SBM?
2. What kind of Markov chain is needed for degree-corrected SBM in this implementation? The original degree-corrected SBM does not do MC I suppose.

Thank you.

**Comment by ntamas** [comment]
1. Yes, I think they do (if I remember correctly). I was trying to stick to the original degree-corrected SBM paper.
2. Currently I use a Markov chain where possible transitions are defined by moving a single vertex into another group. In each step, a transition is chosen according to the Metropolis-Hastings algorithm (i.e. I pick a random vertex, move it to a randomly selected new group, then check the log-likelihood of the old and the new configuration. If the log-likelihood improved, I keep the new configuration unconditionally, otherwise I keep the new configuration with a probability equal to the likelihood ratios of the old and the new configuration. Sampling continues until convergence, where convergence is detected by comparing the average log-likelihood of two consecutive blocks of 65536 samples (can be configured from the command line). If the difference between the two average log-likelihoods is less than 1.0, we assume that the Markov chain converged. `convergence.hpp` and `optimization.hpp` contain more than one convergence criterion and optimization strategy, but I have settled upon this one.

**Comment by yamaguchiyuto** [comment]
Nice, thanks.
